on:
  push:
  workflow_dispatch:

jobs:
  run-build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Run Build Project
        env:
          AI__ApiKey: ${{ secrets.AI__APIKEY }}
          AI__EndPoint: ${{ secrets.AI__ENDPOINT }}
          AI__ModelId: ${{ secrets.AI__MODELID }}
          NuGet__ApiKey: ${{ secrets.NUGET__APIKEY }}
          NuGet__Url: ${{ vars.NUGET__URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet run --project Build/Build.csproj